### ISSUE TITLE
[Suggestion] Call classes dynamic options

### ISSUE THREAD

**Issue by twify93** [LeaseWeb/LswApiCallerBundle#13]
Hello,
I'm currently using this bundle for api calls, but I needed to extend the Call requests to fit more flexible env. My suggestion is this:
```
    public function __construct($url, $requestObject, $asAssociativeArray = false, array $ymlOptions = array())
    {
        parent::__construct($url, $requestObject, $asAssociativeArray);
        $this->ymlOptions = $ymlOptions;
    }
    
    public function makeRequest($curl, $options)
    {
        // merge the options from the API Caller bundle with other set of options
        // override the options with the provided from the Yml
        foreach($this->ymlOptions as $const => $value)
        {
            $options[constant($const)] = $value;
        }
        // call the parent MakeRequest, this way we don't have to copy all it's logic
        parent::makeRequest($curl, $options);
    }
```
My extension is to dynamically put options on the Request. In my case I pass options about the credentials because the Live and Test credentials are different.

Regards,
Lachezar Lechev

**Comment by mevdschee** [comment]
does the change in v1.1.4 fit your needs?

**Comment by mevdschee** [comment]
or the change in v1.2.0 where you can pass an options parameter in the constructor?

**Comment by twify93** [comment]
Yes, v1.2.0 seems great solution to the problem. Thank you.
