### ISSUE TITLE
Can't get headers in version v1.2.0

### ISSUE THREAD

**Issue by jaxel87** [LeaseWeb/LswApiCallerBundle#18]
returntransfer: true
verbose: true
header: true

**Comment by mevdschee** [comment]
Are you calling "getResponseHeaderObject()" to get the headers? Or do you expect them to be returned?

**Comment by jaxel87** [comment]
I was expecting the headers in api_caller call result. Didn't notice function getResponseHeaderObject()

**Comment by mevdschee** [comment]
Good, if you have any further questions, please re-open this issue or open an new one.
