### ISSUE TITLE
POST json format

### ISSUE THREAD

**Issue by jpillias** [LeaseWeb/LswApiCallerBundle#25]
Hi,

Is it possible to POST as JSON. Tried to add the 'Content-type: application/json' header, but can't post a json string :( 
Using HttpPostJson always need add an array, and encode all elements of this array with an url_encode. 

Any solution?

Thank you.

**Comment by jpillias** [comment]
Just see that their is a PR for it (https://github.com/LeaseWeb/LswApiCallerBundle/pull/24/commits/3544f5e43677c86d9ee7a114a4ac4edc4b70300f)

Could you accept it ?

**Comment by mevdschee** [comment]
PUT and POST with JSON body are now supported in new classes.

**Comment by jpillias** [comment]
It seem's the PR is not on the master !

https://github.com/LeaseWeb/LswApiCallerBundle/blob/master/Call/HttpPostJson.php : the extend is still CurlCall instead of HttpPost
And http_build_query instead of json_encode !

**Comment by mevdschee** [comment]
@jpillias: can I help you? Do you have a question?

**Comment by jpillias** [comment]
Just seen your last answer about HttpPostJsonBody.
Will try this today. Maybe should you put the HttpPostJsonBody in the documentation to :)

Thank you for your help.

**Comment by mevdschee** [comment]
Please do a pull request for the patch-1 you have on your fork. It seems like a good addition to me.
