### ISSUE TITLE
Upload files is not supported

### ISSUE THREAD

**Issue by IvanBinzz** [LeaseWeb/LswApiCallerBundle#29]
Using your bundle I have some problems.
Your Bundle is  not support uploading files.
Method "generateRequestData()" always generate QueryString but when I  need  to upload file I need to put array to CURLOPT_POSTFIELDS. I'm ready to fix this problem.

I'm propose remove method "generateRequestData()". And transform data in method  "makeRequest()". 
Variable $requestData use only "Logger". Maybe we not need to log long requests (when post request so big).

Currently I'm solve this problem:

  ```
$result = $this->getContainer()->get('api_caller')->call(
            new HttpPost($url, [], false, [
                'POSTFIELDS' => $post
            ])
        );
```
Why your bundle concat  "CURLOPT_" prefix?? Maybe you need to use class constants???

**Comment by alexndlm** [comment]
ping

**Comment by mevdschee** [comment]
Hi. I wrote the code and used to work for LeaseWeb, but not anymore. Maybe you should try doing a PR. I am sure somebody from LeaseWeb is willing to merge it.
