### ISSUE TITLE
Should not force sslversion.

### ISSUE THREAD

**Issue by sam0737** [LeaseWeb/LswApiCallerBundle#30]
SSLv3 is deprecated, and actually removed in Ubuntu 16.04 LTS+PHP 7. We shouldn't force cURL in using any particular version.

**Comment by mevdschee** [comment]
Fully agree! This was to work around some bug in 12.04 I believe, but I don't remember exactly.

**Comment by sam0737** [comment]
i also vaguely remember that when connecting to a particular SSL server I needed to force sslv3 a couple of years ago - because the auto negotiated result (TLSv*) didn't work. But that was for connecting to one particular server setup only.

**Comment by mevdschee** [comment]
Remove this line from the config:

https://github.com/LeaseWeb/LswApiCallerBundle/blob/master/Resources/config/config.yml#L7

**Comment by mevdschee** [comment]
@GabrielAnca Can you merge this?

**Comment by GabrielAnca** [comment]
Hi @sam0737 I have merged @mevdschee pull request and released a new version of the bundle (1.2.8). Please feel free to update it so you will immediately benefit of this bugfix.

Regards!
