### ISSUE TITLE
New tag

### ISSUE THREAD

**Issue by lbcd** [LeaseWeb/LswApiCallerBundle#45]
Hello,

Can you tag master as a new version please? As it fix an issue on Inflector it would be great to set a tag and not master in composer.

Thank you,

Louis

**Comment by mevdschee** [comment]
@nrocco ?

**Comment by nrocco** [comment]
I will look into creating a new tag later this week.

**Comment by nrocco** [comment]
Apologies for this very late reply, but I have just created tag `v1.2.12`.
